/**
* This file is auto-generated by grpc-helper
*/

import * as grpc from '@midwayjs/grpc';

export namespace helloworld {
  // The greeting service definition.
  export interface Greeter {
    // Sends a greeting
    sayHello(data: HelloRequest): Promise<HelloReply>;
  }
  /**
   * Greeter client interface
   */
  export interface GreeterClient {
    // Sends a greeting
    sayHello(): grpc.IClientUnaryService<HelloRequest, HelloReply>;
  }
  // The request message containing the user&#x27;s name.
  export interface HelloRequest {
    name?: string;
  }
  // The response message containing the greetings
  export interface HelloReply {
    message?: string;
  }
}

