/**
* This file is auto-generated by grpc-helper
*/

import { Metadata } from '@grpc/grpc-js';

export namespace helloworld {
  // The greeting service definition.
  export interface Greeter {
    // Sends a greeting
    sayHello(data: HelloRequest, metadata?: Metadata): Promise<HelloReply>;
  }
  // The request message containing the user&#x27;s name.
  export interface HelloRequest {
    name?: string;
  }
  // The response message containing the greetings
  export interface HelloReply {
    message?: string;
  }
}

